export const PUSH_NOTIFICATION_PENDING = 'PUSH_NOTIFICATION_PENDING';
export const PUSH_NOTIFICATION_SUCCESS = 'PUSH_NOTIFICATION_SUCCESS';
export const PUSH_NOTIFICATION_FAILURE = 'PUSH_NOTIFICATION_FAILURE';
